language: cpp
script: cd tests && sh travis_run_tests.sh
os: linux
dist: trusty
sudo: required
addons:
  apt:
    packages:
      - realpath
services:
  - docker
before_install:
  - echo 'do not install docker on travis ci'
  - sed -i 's/sudo apt-get/#sudo apt-get/g' ./3rd-party/cpv-manage-scripts/scylla/docker_setup.sh
  - sed -i 's/sudo usermod/#sudo usermod/g' ./3rd-party/cpv-manage-scripts/scylla/docker_setup.sh
  - sed -i 's/sudo systemctl/#sudo systemctl/g' ./3rd-party/cpv-manage-scripts/scylla/docker_setup.sh
  - echo
  - echo 'prepare test environment'
  - cd tests && sudo sh prepare.sh && cd ..
  - echo

