language: cpp
script: cd tests && sh run_tests.sh
os: linux
dist: trusty
sudo: required
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: 'deb http://ppa.launchpad.net/scylladb/ppa/ubuntu trusty main'
    packages:
      - g++-8
      - cmake
      - scylla-libboost163-all-dev
      - realpath
services:
  - docker
git:
  submodules: false
before_install:
  - echo 'fix submodule'
  - sed -i 's/ssh:\/\/git@github.com\//https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - echo
  - echo 'do not install docker on travis ci'
  - sed -i 's/sudo apt-get/#sudo apt-get/g' ./3rd-party/cpv-manage-scripts/scylla/docker_setup.sh
  - sed -i 's/sudo usermod/#sudo usermod/g' ./3rd-party/cpv-manage-scripts/scylla/docker_setup.sh
  - sed -i 's/sudo systemctl/#sudo systemctl/g' ./3rd-party/cpv-manage-scripts/scylla/docker_setup.sh
  - echo
  - echo 'install dependencies'
  - sed -i 's/libboost-all-dev//g' ./3rd-party/seastar/install-dependencies.sh
  - sed -i 's/g++-5/g++-8/g' ./3rd-party/seastar/install-dependencies.sh
  - sudo sh install-dependencies.sh
  - cd tests && sudo sh prepare.sh && cd ..
  - echo
  - echo 'fix build options'
  - sed -i 's/configure.py/configure.py --c-compiler gcc-8 --compiler g++-8 --cflags=-I\/opt\/scylladb\/include --ldflags=-L\/opt\/scylladb\/lib\/x86_64-linux-gnu/g' build-debug.sh
  - export CC=gcc-8
  - export CXX=g++-8

