language: cpp
script: cd tests && sh run_tests.sh
os: linux
dist: trusty
sudo: required
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - realpath
services:
  - docker
git:
  submodules: false
before_install:
  - echo 'fix submodule'
  - sed -i 's/ssh:\/\/git@github.com\//https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - echo
  - echo 'do not install docker on travis ci'
  - sed -i 's/sudo apt-get/#sudo apt-get/g' ./3rd-party/cpv-manage-scripts/scylla/docker_setup.sh
  - sed -i 's/sudo usermod/#sudo usermod/g' ./3rd-party/cpv-manage-scripts/scylla/docker_setup.sh
  - sed -i 's/sudo systemctl/#sudo systemctl/g' ./3rd-party/cpv-manage-scripts/scylla/docker_setup.sh
  - echo
  - echo 'create scylla containers'
  - cd tests && sudo sh prepare.sh
  - echo
  - export CC=gcc-7
  - export CXX=g++-7

